name: Build and Publish .NET Framework 4.8 Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1   

    - name: Restore NuGet packages
      run: nuget restore ScanSpectre.sln

    - name: Build solution
      run: |
        $OutputDir = "C:\Publish"
        mkdir $OutputDir
        msbuild /p:Configuration=Release ScanSpectre.sln/p:OutputPath=$OutputDir

    - name: Create a ZIP archive of the published files
      run: |
        Compress-Archive -Path C:\Publish\* -DestinationPath C:\Publish\release.zip

    - name: Upload release artifact
      uses: actions/upload-artifact@v3
      with:
        name: release-$(date +'%Y%m%d%H%M%S')
        path: C:\Publish\release.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create GitHub release
      uses: gh actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: 'Release description here.'
        draft: false
        prerelease: false

    - name: Upload release asset
      uses: gh actions/upload-release-asset@v1
      with:
        release_id: ${{ steps.create_release.outputs.id }}
        asset_path: C:\Publish\release.zip
        asset_name: release.zip
        asset_content_type: application/zip
