name: Build and Publish .NET Framework 4.8 Release

permissions:
  contents: write
  discussions: write

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1   
    
    - name: Restore NuGet packages
      run: dir

    - name: Restore NuGet packages
      run: nuget restore D:\a\ScanSpectre\ScanSpectre\ScanSpectre.sln

    - name: Build solution
      run: |
        $OutputDir = "C:\Publish"
        mkdir $OutputDir
        msbuild /p:Configuration=Release D:\a\ScanSpectre\ScanSpectre\ScanSpectre.sln /p:OutputPath=$OutputDir

    - name: Create a ZIP archive of the published files
      run: |
        Compress-Archive -Path C:\Publish\* -DestinationPath C:\Publish\release.zip

    - name: Upload release artifact
      uses: actions/upload-artifact@v3
      with:
        name: release-$(date +'%Y%m%d%H%M%S')
        path: C:\Publish\release.zip
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: C:\Publish\release.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
