name: Build and Publish .NET Framework 4.8 Release

permissions:
  contents: write
  discussions: write

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1     

    - name: Restore NuGet packages
      run: nuget restore "${{ github.workspace }}\ScanSpectre\ScanSpectre.csproj"

    - name: Build project
      run: |
        $OutputDir = "${{ github.workspace }}\Publish"
        mkdir $OutputDir
        msbuild "${{ github.workspace }}\ScanSpectre\ScanSpectre.csproj" /p:Configuration=Release /p:OutDir=$OutputDir\

    - name: Create ZIP archive
      run: Compress-Archive -Path "${{ github.workspace }}\Publish\*" -DestinationPath "${{ github.workspace }}\Publish\release.zip"
        
    - name: Create Git tag
      id: set_tag
      shell: bash
      run: |
        tag="v$(date +'%Y%m%d%H%M%S')"
        git tag "$tag"
        git push origin "$tag"
        echo "TAG=$tag" >> $GITHUB_ENV

    - name: Create GitHub release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TAG }}
        release_name: Release ${{ env.TAG }}

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: "${{ github.workspace }}\Publish\release.zip"
        asset_name: ScanSpectre.zip
        asset_content_type: application/zip
